#!/bin/bash

# Commands to remove the dark-mode theme from the database

echo "🗑️  Removing dark-mode theme from database..."
echo ""
echo "Choose one method:"
echo ""
echo "=========================================="
echo "METHOD 1: Using Prisma Studio (GUI)"
echo "=========================================="
echo "1. Run: npx prisma studio"
echo "2. Navigate to FormTheme table"
echo "3. Find the record with id='dark-mode'"
echo "4. Click the trash icon to delete it"
echo ""
echo "=========================================="
echo "METHOD 2: Using Prisma Client (TypeScript)"
echo "=========================================="
echo "Run this command in your Next.js app:"
echo ""
echo "  npx tsx -e \"import { prisma } from './src/lib/db'; await prisma.formTheme.delete({ where: { id: 'dark-mode' } }).then(() => console.log('✅ Dark mode theme deleted')).catch(e => console.error('❌ Error:', e)).finally(() => prisma.\\\$disconnect())\""
echo ""
echo "=========================================="
echo "METHOD 3: Direct PostgreSQL command"
echo "=========================================="
echo "Connect to your database and run:"
echo ""
echo "  DELETE FROM \"FormTheme\" WHERE id = 'dark-mode';"
echo ""
echo "=========================================="
echo "METHOD 4: Using psql CLI"
echo "=========================================="
echo "Run this one-liner:"
echo ""
echo "  psql \$DATABASE_URL -c \"DELETE FROM \\\"FormTheme\\\" WHERE id = 'dark-mode';\""
echo ""
echo "=========================================="
echo ""
echo "After deleting, reseed the themes with:"
echo "  npx tsx prisma/seed-themes.ts"
echo ""
