import type { Metadata } from "next";
import { Providers } from './providers';
import ConditionalFooter from "@/components/shared/ConditionalFooter";
import PostHogPageView from '@/components/shared/PostHogPageView';
import Script from "next/script";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <Script
          src={process.env.NEXT_PUBLIC_UMAMI_SCRIPT_URL}
          data-website-id={process.env.NEXT_PUBLIC_UMAMI_WEBSITE_ID}
          strategy="afterInteractive"
        />
      </head>
      <body
        className={`antialiased`}
      >
        <Providers>
          <PostHogPageView />
          {children}
          <ConditionalFooter />
        </Providers>
      </body>
    </html>
  );
}
